version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    target-branch: "main"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Shanghai"
    allow:
      - dependency-name: "org.springframework*"
        dependency-type: "all"
