version: 2

updates:
  - package-ecosystem: "maven"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:50"
      timezone: "Asia/Shanghai"
    allow:
      - dependency-name: "org.springframework*"
        dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]