# https://github.com/toolmantim/release-drafter

# 新项目，第一次 release 为 0.1.0, 可以在 github 上手动修改为 0.0.1
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 🚀 New features
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug fixes
    labels:
      - bug
      - fix
      - hotfix
      - bugfix
  - title: 📝 Documentation updates
    labels:
      - documentation
      - localization
  - title: 🚦Tests
    labels:
      - test
      - tests
  - title: 🧰 Dependency updates
    labels:
      - dependencies
      - dependabot
      - DEPENDABOT
    collapse-after: 15

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/bugfix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'

template: |
  ## What’s Changed

  $CHANGES

  All contributors: $CONTRIBUTORS