services:
  redis:
    image: redis:7
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli","--raw", "incr","ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  authserver:
    image: "dexidp/dex:v2.37.0"
    deploy:
      replicas: 1
    configs:
      - source: dex_config
        target: /opt/config/dex.yml
    ports:
      - "5556:5556"
    command:
      - dex
      - serve
      - /opt/config/dex.yml
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5556/.well-known/openid-configuration" ]
      interval: 1s
      timeout: 1s
      retries: 5

configs:
  dex_config:
    file: dex.yml

volumes:
  redis: