# keep
server:
  servlet:
    session:
      persistent: false
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://localhost/security5?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: pass
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always


logging:
  level:
    org.springframework.security: trace
