# keep
server:
  servlet:
    session:
      persistent: false
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.security: trace
